
on:
  push:
    branches:
        - master
  pull_request:
  repository_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    name: Build and Deploy
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
      - uses: actions/setup-node@v2      
        with:
          node-version: '14'
          cache: yarn
      - name: Install Dependencies
        run: yarn install
      - name: Build
        run: yarn build        
      - name: Publish Worker
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
